/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */

declare module "sst" {
  export interface Resource {
    "NEXT_PUBLIC_API_ID": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "NEXT_PUBLIC_SITE_URL": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "NEXT_PUBLIC_SUPABASE_ANON_KEY": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "NEXT_PUBLIC_SUPABASE_URL": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "Website": {
      "type": "sst.aws.Nextjs"
      "url": string
    }
  }
}
/// <reference path="sst-env.d.ts" />

import "sst"
export {}